-- =============================================================================
-- COMPLETE DATABASE SETUP — MICROSOFT TO-DO CLONE
-- Supabase (Postgres)
-- =============================================================================

-- =============================================================================
-- 1. TABLES
-- =============================================================================

create table public.users (
  user_id bigint generated by default as identity primary key,
  user_email text not null unique,
  user_fullname text not null,
  user_clerk_id text unique,
  user_created_at timestamp with time zone default now()
);

create table public.categories (
  category_owner_id bigint references public.users(user_id),
  category_title text not null,
  category_created_at timestamp with time zone default now(),
  has_category_invitation boolean not null default false,
  category_id uuid not null primary key,
  has_category_collaborator boolean not null default false
);

create table public.tasks (
  task_title text not null,
  task_note text,
  is_task_starred boolean default false,
  task_due_date timestamp with time zone,
  task_created_at timestamp with time zone,
  task_updated_at timestamp with time zone,
  is_task_completed boolean default false,
  task_id uuid not null primary key,
  task_reminder timestamp with time zone,
  task_repeat text,
  task_completed_at timestamp with time zone,
  is_task_in_myday boolean default false,
  task_steps jsonb,
  task_owner_id bigint not null references public.users(user_id),
  task_category_id uuid not null references public.categories(category_id) on delete cascade,
  task_category_title text
);

create table public.invitations (
  invitation_id uuid not null default gen_random_uuid() primary key,
  invitation_category_id uuid not null references public.categories(category_id) on delete cascade,
  invitation_owner_id bigint not null references public.users(user_id),
  invitation_created_at timestamp with time zone default now(),
  invitation_limit_access boolean not null default false
);

create table public.collaborators (
  invitation_id uuid not null references public.invitations(invitation_id) on delete cascade,
  user_id bigint not null references public.users(user_id),
  primary key (invitation_id, user_id)
);

create table public.errors_log (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  method text,
  message text
);

create table public.health_check (
  id uuid not null default gen_random_uuid() primary key,
  status text,
  last_updated timestamp without time zone default now()
);

-- =============================================================================
-- 2. DEFAULT DATA
-- =============================================================================

-- default "Tasks" category (every user sees only their own tasks inside it)
insert into public.categories (
  category_id,
  category_title,
  category_owner_id,
  has_category_invitation,
  has_category_collaborator
) values (
  '00000000-0000-0000-0000-000000000000',
  'Tasks',
  null,
  false,
  false
) on conflict (category_id) do nothing;

-- minimal health‑check row so the app can verify DB connectivity
insert into public.health_check (status) values ('ok');

-- =============================================================================
-- 3. HELPER FUNCTIONS (SECURITY DEFINER)
-- =============================================================================

-- map Clerk JWT sub to internal user ID
create or replace function public.requesting_user_id()
returns bigint
language sql
stable
security definer
set search_path = 'public'
as $$
  select user_id
  from public.users
  where user_clerk_id = (auth.jwt() ->> 'sub')
  limit 1;
$$;

-- is the current user the owner of this category?
create or replace function public.is_category_owner(category_id uuid)
returns boolean
language sql
stable
security definer
set search_path = 'public'
as $$
  select exists (
    select 1 from public.categories c
    where c.category_id = $1
      and c.category_owner_id = requesting_user_id()
  );
$$;

-- is the current user a collaborator of this category?
create or replace function public.is_category_collaborator(category_id uuid)
returns boolean
language sql
stable
security definer
set search_path = 'public'
as $$
  select exists (
    select 1
    from public.invitations i
    join public.collaborators col on i.invitation_id = col.invitation_id
    where i.invitation_category_id = $1
      and col.user_id = requesting_user_id()
  );
$$;

-- full task access check (default / unshared / shared)
create or replace function public.can_access_task(task_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = 'public'
as $$
declare
  v_category_id uuid;
  v_owner_id bigint;
begin
  select t.task_category_id, t.task_owner_id
    into v_category_id, v_owner_id
    from public.tasks t
    where t.task_id = $1;

  -- default category: only the task owner
  if v_category_id = '00000000-0000-0000-0000-000000000000' then
    return v_owner_id = requesting_user_id();
  end if;

  -- custom categories: owner or collaborator can access
  return is_category_owner(v_category_id) or is_category_collaborator(v_category_id);
end;
$$;

-- =============================================================================
-- 4. RPC FUNCTIONS (SECURITY DEFINER)
-- =============================================================================

-- get profile of a collaborator (only if they share a list with the current user)
create or replace function public.get_collaborator_profile(param_user_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = 'public'
as $$
  select to_jsonb(u) - 'user_clerk_id'
  from public.users u
  where u.user_id = param_user_id
    and exists (
      select 1
      from public.collaborators c1
      join public.collaborators c2 on c1.invitation_id = c2.invitation_id
      where c1.user_id = requesting_user_id()
        and c2.user_id = param_user_id
    );
$$;

-- list of shared lists the current user has joined (excluding those they own)
create or replace function public.get_joined_invitations()
returns setof jsonb
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_user_id bigint;
  v_invitation_id uuid;
  v_category_id uuid;
  v_category_owner_id bigint;
begin
  v_user_id := requesting_user_id();

  for v_invitation_id, v_category_id, v_category_owner_id in
    select i.invitation_id, i.invitation_category_id, c.category_owner_id
    from public.invitations i
    join public.collaborators col on i.invitation_id = col.invitation_id
    join public.categories c on i.invitation_category_id = c.category_id
    where col.user_id = v_user_id
      and i.invitation_owner_id != v_user_id
  loop
    return next jsonb_build_object(
      'invitation_id', v_invitation_id,
      'invitation_category_id', v_category_id,
      'invitation_category_owner_id', v_category_owner_id
    );
  end loop;

  return;
end;
$$;

-- all invitations created by the current user, including the member list
create or replace function public.get_owner_invitations()
returns setof jsonb
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_user_id bigint;
  v_invitation_id uuid;
  v_invitation_category_id uuid;
  v_invitation_limit_access boolean;
  v_invitation_created_at timestamptz;
  v_shared_with jsonb;
begin
  v_user_id := requesting_user_id();

  for v_invitation_id, v_invitation_category_id, v_invitation_limit_access, v_invitation_created_at
  in
    select invitation_id, invitation_category_id, invitation_limit_access, invitation_created_at
    from public.invitations
    where invitation_owner_id = v_user_id
  loop
    select jsonb_agg(
      jsonb_build_object(
        'user_id', u.user_id,
        'user_name', u.user_fullname,
        'user_email', u.user_email
      )
    )
    into v_shared_with
    from public.collaborators c
    join public.users u on c.user_id = u.user_id
    where c.invitation_id = v_invitation_id;

    v_shared_with := coalesce(v_shared_with, '[]'::jsonb);

    return next jsonb_build_object(
      'invitation_id', v_invitation_id,
      'invitation_category_id', v_invitation_category_id,
      'invitation_owner_id', v_user_id,
      'invitation_limit_access', v_invitation_limit_access,
      'invitation_created_at', v_invitation_created_at,
      'sharedWith', v_shared_with
    );
  end loop;

  return;
end;
$$;

-- categories relevant to the current user (owned + joined)
create or replace function public.get_relevent_categories()
returns setof public.categories
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_user_id bigint;
begin
  v_user_id := requesting_user_id();

  return query
  (
    select c.*
    from public.categories c
    where c.category_owner_id = v_user_id

    union

    select c.*
    from public.categories c
    join public.invitations i on c.category_id = i.invitation_category_id
    join public.collaborators col on i.invitation_id = col.invitation_id
    where col.user_id = v_user_id
  );
end;
$$;

-- all tasks the current user can access (own tasks + tasks in shared lists)
create or replace function public.get_relevent_tasks()
returns setof public.tasks
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_user_id bigint;
  v_category_id uuid;
  v_invitation_id uuid;
begin
  v_user_id := requesting_user_id();

  create temp table temp_tasks (like public.tasks including all) on commit drop;

  insert into temp_tasks
  select * from public.tasks
  where task_owner_id = v_user_id;

  for v_invitation_id in
    select invitation_id from public.collaborators where user_id = v_user_id
  loop
    select invitation_category_id into v_category_id
    from public.invitations where invitation_id = v_invitation_id;

    if v_category_id is not null then
      insert into temp_tasks
      select * from public.tasks
      where task_category_id = v_category_id
      on conflict (task_id) do nothing;
    end if;
  end loop;

  return query select distinct * from temp_tasks;
end;
$$;

-- create an invitation for a category (owner only)
create or replace function public.invitation_create(param_category_id uuid)
returns uuid
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_category_exists boolean;
  v_invitation_id uuid;
  v_owner_id bigint;
begin
  v_owner_id := requesting_user_id();

  select exists (
    select 1 from public.categories
    where category_id = param_category_id
      and category_owner_id = v_owner_id
  ) into v_category_exists;

  if not v_category_exists then
    raise exception 'Category not found or does not belong to you.';
  end if;

  v_invitation_id := gen_random_uuid();

  insert into public.invitations (
    invitation_id,
    invitation_category_id,
    invitation_owner_id,
    invitation_limit_access
  ) values (
    v_invitation_id,
    param_category_id,
    v_owner_id,
    false
  );

  update public.categories
  set has_category_invitation = true
  where category_id = param_category_id;

  insert into public.collaborators (invitation_id, user_id)
  values (v_invitation_id, v_owner_id)
  on conflict do nothing;

  return v_invitation_id;
exception
  when others then
    raise exception 'Transaction failed: %', sqlerrm;
end;
$$;

-- join a shared list using an invitation link
create or replace function public.invitation_join(param_invitation_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_user_id bigint;
  v_associated_category_id uuid;
  v_is_access_limited boolean;
begin
  v_user_id := requesting_user_id();

  select invitation_category_id, invitation_limit_access
  into v_associated_category_id, v_is_access_limited
  from public.invitations
  where invitation_id = param_invitation_id;

  if not found then
    raise exception 'Invitation not found.';
  end if;

  -- existing members can always re‑access, even if limit was turned on later
  if exists (
    select 1 from public.collaborators
    where invitation_id = param_invitation_id and user_id = v_user_id
  ) then
    return jsonb_build_object(
      'category',
      (select to_jsonb(cat) from public.categories cat where cat.category_id = v_associated_category_id),
      'tasks',
      coalesce(
        (select jsonb_agg(to_jsonb(task)) from public.tasks task where task.task_category_id = v_associated_category_id),
        '[]'::jsonb
      )
    );
  end if;

  -- only block NEW joins when access is limited
  if v_is_access_limited then
    raise exception 'Access is limited for this invitation.';
  end if;

  insert into public.collaborators (invitation_id, user_id)
  values (param_invitation_id, v_user_id);

  update public.categories
  set has_category_collaborator = true
  where category_id = v_associated_category_id;

  return jsonb_build_object(
    'category',
    (select to_jsonb(cat) from public.categories cat where cat.category_id = v_associated_category_id),
    'tasks',
    coalesce(
      (select jsonb_agg(to_jsonb(task)) from public.tasks task where task.task_category_id = v_associated_category_id),
      '[]'::jsonb
    )
  );
end;
$$;

-- leave a shared list (collaborators only; owner must use stop_sharing)
create or replace function public.invitation_leave(p_invitation_id uuid)
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_user_id bigint;
  v_category_id uuid;
  v_owner_id bigint;
begin
  v_user_id := requesting_user_id();

  select invitation_category_id, invitation_owner_id
  into v_category_id, v_owner_id
  from public.invitations
  where invitation_id = p_invitation_id;

  if v_category_id is null then
    raise exception 'Invitation not found.';
  end if;

  if v_owner_id = v_user_id then
    raise exception 'Owner cannot leave their own invitation, use invitation_stop_sharing instead.';
  end if;

  delete from public.collaborators
  where invitation_id = p_invitation_id and user_id = v_user_id;

  if not found then
    raise exception 'You are not a collaborator on this invitation.';
  end if;

  if not exists (
    select 1 from public.collaborators where invitation_id = p_invitation_id
  ) then
    update public.categories
    set has_category_collaborator = false
    where category_id = v_category_id;
  end if;
end;
$$;

-- owner removes a specific collaborator
create or replace function public.invitation_remove_user(param_invitation_id uuid, param_user_id bigint)
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_owner_id bigint;
  v_invitation_category_id uuid;
begin
  v_owner_id := requesting_user_id();

  if not exists (
    select 1 from public.invitations
    where invitation_id = param_invitation_id and invitation_owner_id = v_owner_id
  ) then
    raise exception 'Unauthorized: You are not the owner of this invitation.';
  end if;

  if param_user_id = v_owner_id then
    raise exception 'Owner cannot remove themselves, use invitation_stop_sharing instead.';
  end if;

  delete from public.collaborators
  where invitation_id = param_invitation_id and user_id = param_user_id;

  if not found then
    raise exception 'Collaborator not found.';
  end if;

  select invitation_category_id into v_invitation_category_id
  from public.invitations
  where invitation_id = param_invitation_id;

  if not exists (
    select 1 from public.collaborators where invitation_id = param_invitation_id
  ) then
    update public.categories
    set has_category_collaborator = false
    where category_id = v_invitation_category_id;
  end if;
end;
$$;

-- owner enables/disables new joins via the invite link
create or replace function public.invitation_set_limit(param_invitation_id uuid, param_limit_access boolean)
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_owner_id bigint;
begin
  v_owner_id := requesting_user_id();

  if not exists (
    select 1 from public.invitations
    where invitation_id = param_invitation_id
      and invitation_owner_id = v_owner_id
  ) then
    raise exception 'Unauthorized: You are not the owner of this invitation.';
  end if;

  update public.invitations
  set invitation_limit_access = param_limit_access
  where invitation_id = param_invitation_id;
end;
$$;

-- owner stops sharing entirely (removes all collaborators and the invitation)
create or replace function public.invitation_stop_sharing(param_invitation_id uuid)
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_owner_id bigint;
  v_associated_category_id uuid;
begin
  v_owner_id := requesting_user_id();

  select invitation_category_id into v_associated_category_id
  from public.invitations
  where invitation_id = param_invitation_id and invitation_owner_id = v_owner_id;

  if not found then
    raise exception 'Invitation not found or you are not the owner.';
  end if;

  delete from public.collaborators where invitation_id = param_invitation_id;
  delete from public.invitations where invitation_id = param_invitation_id;

  update public.categories
  set has_category_invitation = false,
      has_category_collaborator = false
  where category_id = v_associated_category_id;
end;
$$;

-- =============================================================================
-- 5. ENABLE ROW LEVEL SECURITY
-- =============================================================================

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.tasks enable row level security;
alter table public.invitations enable row level security;
alter table public.collaborators enable row level security;
alter table public.errors_log enable row level security;
alter table public.health_check enable row level security;

-- =============================================================================
-- 6. RLS POLICIES
-- =============================================================================

-- 6.1 users
drop policy if exists "users_select" on public.users;
create policy "users_select" on public.users for select
  using (user_clerk_id = (auth.jwt() ->> 'sub'));

drop policy if exists "users_insert" on public.users;
create policy "users_insert" on public.users for insert
  with check (user_clerk_id = (auth.jwt() ->> 'sub'));

drop policy if exists "users_update" on public.users;
create policy "users_update" on public.users for update
  using (user_clerk_id = (auth.jwt() ->> 'sub'));

-- 6.2 categories
drop policy if exists "categories_select" on public.categories;
create policy "categories_select" on public.categories for select
  using (
    category_id = '00000000-0000-0000-0000-000000000000'::uuid
    or is_category_owner(category_id)
    or is_category_collaborator(category_id)
  );

drop policy if exists "categories_insert" on public.categories;
create policy "categories_insert" on public.categories for insert
  with check (category_owner_id = requesting_user_id());

drop policy if exists "categories_update" on public.categories;
create policy "categories_update" on public.categories for update
  using (is_category_owner(category_id))
  with check (category_owner_id = requesting_user_id());

drop policy if exists "categories_delete" on public.categories;
create policy "categories_delete" on public.categories for delete
  using (is_category_owner(category_id));

-- 6.3 tasks
drop policy if exists "tasks_select" on public.tasks;
create policy "tasks_select" on public.tasks for select
  using (can_access_task(task_id));

drop policy if exists "tasks_insert" on public.tasks;
create policy "tasks_insert" on public.tasks for insert
  with check (
    task_owner_id = requesting_user_id()
    and (
      task_category_id = '00000000-0000-0000-0000-000000000000'::uuid
      or is_category_owner(task_category_id)
      or is_category_collaborator(task_category_id)
    )
  );

drop policy if exists "tasks_update" on public.tasks;
create policy "tasks_update" on public.tasks for update
  using (can_access_task(task_id));

drop policy if exists "tasks_delete" on public.tasks;
create policy "tasks_delete" on public.tasks for delete
  using (can_access_task(task_id));

-- 6.4 invitations
drop policy if exists "invitations_select" on public.invitations;
create policy "invitations_select" on public.invitations for select
  using (invitation_owner_id = requesting_user_id());

-- 6.5 collaborators
drop policy if exists "collaborators_select" on public.collaborators;
create policy "collaborators_select" on public.collaborators for select
  using (
    user_id = requesting_user_id()
    or exists (
      select 1 from public.invitations i
      where i.invitation_id = collaborators.invitation_id
        and i.invitation_owner_id = requesting_user_id()
    )
  );

-- 6.6 errors_log (only insert for public, nothing else)
drop policy if exists "errors_log_insert" on public.errors_log;
create policy "errors_log_insert" on public.errors_log for insert
  with check (true);

drop policy if exists "errors_log_select" on public.errors_log;
create policy "errors_log_select" on public.errors_log for select using (false);

drop policy if exists "errors_log_update" on public.errors_log;
create policy "errors_log_update" on public.errors_log for update using (false);

drop policy if exists "errors_log_delete" on public.errors_log;
create policy "errors_log_delete" on public.errors_log for delete using (false);

-- 6.7 health_check (public select, no modifications)
drop policy if exists "health_check_select" on public.health_check;
create policy "health_check_select" on public.health_check for select using (true);

drop policy if exists "health_check_insert" on public.health_check;
create policy "health_check_insert" on public.health_check for insert with check (false);

drop policy if exists "health_check_update" on public.health_check;
create policy "health_check_update" on public.health_check for update using (false);

drop policy if exists "health_check_delete" on public.health_check;
create policy "health_check_delete" on public.health_check for delete using (false);